Create patches for untracked files
learnweb/automated-moodle-patching pull request #3
Opened 2019-12-05 10:20 UTC by justusdieckmann

2019-12-05 10:24 UTC, Dagefoerde requested changes

2019-12-05 10:24 UTC, Dagefoerde commented on makepatches.sh
> +  git ls-files -o --exclude-standard -z | xargs -i -0 git diff --no-index -- /dev/null \"{}\" >> \"$patchpath\"
die Backslashes sind über

2019-12-05 10:24 UTC, Dagefoerde commented on makepatches.sh
> +  git ls-files -o --exclude-standard -z | xargs -i -0 git diff --no-index -- /dev/null \"{}\" >> \"$patchpath\"
und klappt das alles auch dann, wenn es NUR neue Dateien aber sonst keinen Diff gibt?

2019-12-05 10:25 UTC, Dagefoerde commented on makepatches.sh
> +  git ls-files -o --exclude-standard -z | xargs -i -0 git diff --no-index -- /dev/null \"{}\" >> \"$patchpath\"
Okay, Backslashes sind doch nicht über. Aber die andere Frage bleibt!

2019-12-09 09:44 UTC, Dagefoerde reviewed
@justusdieckmann hattest du den Fall auch mal ausprobiert? Insbesondere funktioniert das `>>` in:
https://github.com/learnweb/automated-moodle-patching/pull/3/files/cbc40281eb4f6c6d683c183efcf14a30dd478d0f..af944d11ac24556c80224d99e80956bce725b840#diff-b967c699264044e3c96efb3a4a8c06ddR37
auch dann sinnvoll, wenn in der Zeile davor noch keine Datei angelegt wurde?

2019-12-09 11:48 UTC, justusdieckmann commented
Jop, den Fall hab ich ausprobiert. (Allerdings nur unter den neuen Git/Bash-Versionen). Der `>>`-Operator erstellt auch die Datei, falls sie noch nicht existiert. (http://man7.org/linux/man-pages/man1/bash.1.html bei 'Appending Redirected Output')

2019-12-09 12:22 UTC, Dagefoerde approved these changes

2019-12-09 12:22 UTC, merged